name: CI Run e2e Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose for tests
        run: docker-compose up -d db_test
      - name: Check running containers
        run: docker ps -a
      - name: Install dependencies
        run: yarn install
      - name: Run e2e tests
        run: yarn test:e2e
